name: Idempotent Buildx amd64/arm4 Multiplatform Image

on:
  workflow_call:

    secrets:
      registry_u:
        description: The username for the docker login
        required: true
      registry_p:
        description: The password (PAT) for the docker login
        required: true

    inputs:
      image:
        description: The name of the image to build and push
        required: true
        type: string
      buildopts:
        description: Optional docker buildx options e.g. --target
        type: string
      runner_general:
        description: "The type of runner for the general jobs in workflow (ubuntu-24.04-arm)"
        required: false
        type: string
        default: ubuntu-24.04-arm
      runner_amd64:
        description: "The type of linux/amd64 runner for this workflow (ubuntu-latest)"
        required: false
        type: string
        default: ubuntu-latest
      amd64_tag:
        description: "The amd64 architecture tag/name (amd64)"
        required: false
        type: string
        default: amd64
      amd64_platform:
        description: "The amd64 platform(linux/amd64)"
        required: false
        type: string
        default: linux/amd64
      runner_arm64:
        description: "The type of linux/arm64 runner for this workflow (ubuntu-24.04-arm)"
        required: false
        type: string
        default: ubuntu-24.04-arm
      arm64_tag:
        description: "The arm64 architecture tag/name"
        required: false
        type: string
        default: arm64
      arm64_platform:
        description: "The arm64 platform(linux/arm64)"
        required: false
        type: string
        default: linux/arm64
      summary:
        description: "Add a summary report to the workflow run (true)"
        required: false
        type: boolean
        default: true
      # Registry build caches
      edge_build_cache_name:
        description: 'The name of the global "edge" build cache'
        required: false
        type: string
      root_build_cache_name:
        description: 'The name of the global "root" build cache'
        required: false
        type: string
      branch_build_cache_name:
        description: 'The name of the global "branch" build cache'
        required: false
        type: string

jobs:

  platform-image-names:
   name: Set the platform image name if building
   runs-on: ${{ inputs.runner_general }}
   env:
    AMD_IMAGE: ${{ inputs.image }}-${{ inputs.amd64_tag }}
    ARM_IMAGE: ${{ inputs.image }}-${{ inputs.arm64_tag }}
   outputs:
    amd-name: ${{ steps.if-build.outputs.amd-name }}
    arm-name: ${{ steps.if-build.outputs.arm-name }}
   steps:
    - id: if-build
      run: |
        [ -n "${{ inputs.runner_amd64 }}" ] && echo "amd-name=${AMD_IMAGE}" >> $GITHUB_OUTPUT || true
        [ -n "${{ inputs.runner_arm64 }}" ] && echo "arm-name=${ARM_IMAGE}" >> $GITHUB_OUTPUT || true

    - name: Verify a platform
      run: |
        if [ -z "${{ steps.if-build.outputs.amd-name }}" ] && [ -z "${{ steps.if-build.outputs.arm-name }}" ]; then
          # Error: No platforms to build

          error_message='At least one platform must be built - no platform runners specified'
          echo "${error_message}"

          # Annotate error
          echo "::error::${error_message}"

          # Summary of error
          summary="<b>:x: ${error_message}</b>"
          echo "${summary}" >> $GITHUB_STEP_SUMMARY

          # EXIT
          exit 1
        fi

        echo "AMD Platform Image: [${{ steps.if-build.outputs.amd-name }}]"
        echo "ARM Platform Image: [${{ steps.if-build.outputs.arm-name }}]"

  buildx-and-push-image:
    name: Build and Push Platform Image
    needs: platform-image-names
    runs-on: ${{ matrix.platform.runner || inputs.runner_general }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ${{ inputs.amd64_tag }}
            runner: ${{ inputs.runner_amd64 }}
            image: ${{ needs.platform-image-names.outputs.amd-name }}
            value: ${{ inputs.amd64_platform }}
          - name: ${{ inputs.arm64_tag }}
            runner: ${{ inputs.runner_arm64 }}
            image: ${{ needs.platform-image-names.outputs.arm-name }}
            value: ${{ inputs.arm64_platform }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        if:  matrix.platform.image

      - name: Image name
        if:  matrix.platform.image
        run: echo "Image name [${{ matrix.platform.image }}]"

      - name: Login to DockerHub registry
        if:  matrix.platform.image
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        if:  matrix.platform.image

      - name: Buildx and push image
        if:  matrix.platform.image
        env:
          DOCKER_BUILDKIT: 1
          BUILDOPTS: ${{ inputs.buildopts }}
        run: |
          # Edge cache is both read and write
          if [ -n "${{ inputs.edge_build_cache_name }}" ] ; then
            edge_cache_name="${{ inputs.edge_build_cache_name }}-${{ matrix.platform.name }}"
            echo "Using Edge Cache: [${edge_cache_name}]"

            BUILDOPTS="${BUILDOPTS} --cache-from type=registry,ref=${edge_cache_name}"
            BUILDOPTS="${BUILDOPTS} --cache-to type=registry,ref=${edge_cache_name},mode=max"
          fi

          # Root cache is read only
          if [ -n "${{ inputs.root_build_cache_name }}" ] ; then
            root_cache_name="${{ inputs.root_build_cache_name }}-${{ matrix.platform.name }}"
            echo "Using Root Cache: [${root_cache_name}]"

            BUILDOPTS="${BUILDOPTS} --cache-from type=registry,ref=${root_cache_name}"
          fi

          # Branch cache is both read and write
          if [ -n "${{ inputs.branch_build_cache_name }}" ] ; then
            branch_cache_name="${{ inputs.branch_build_cache_name }}-${{ matrix.platform.name }}"
            echo "Using Branch Cache: [${branch_cache_name}]"

            BUILDOPTS="${BUILDOPTS} --cache-from type=registry,ref=${branch_cache_name}"
            BUILDOPTS="${BUILDOPTS} --cache-to type=registry,ref=${branch_cache_name},mode=max"
          fi
          echo "Build options..."
          echo ["${BUILDOPTS}"]

          docker pull ${{ matrix.platform.image }} \
          || docker buildx build \
            ${BUILDOPTS} \
            --push --platform ${{ matrix.platform.value }} \
            --tag ${{ matrix.platform.image }} \
            .

      - name: Logout of DockerHub registry
        if:  matrix.platform.image
        run: docker logout

      - name: Platform build summary
        if:  matrix.platform.image
        run: |
          image_fragment="<code>${{ matrix.platform.image }}</code>"
          summary="<b>Built and Pushed <code>${{ matrix.platform.name }}</code> Image:</b><br>${image_fragment}"
          echo "${summary}" >> $GITHUB_STEP_SUMMARY

  combine-images:
    name: Create Multiplatform Image
    runs-on: ${{ inputs.runner_general }}
    needs:
      - platform-image-names
      - buildx-and-push-image
    env:
      IMAGE: ${{ inputs.image }}
      AMD_IMAGE: ${{ needs.platform-image-names.outputs.amd-name }}
      ARM_IMAGE: ${{ needs.platform-image-names.outputs.arm-name }}

    steps:

      - name: Login to DockerHub registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multiplatform image
        run: |
          # AT least one platform image is expected/must exist
          PLATFORM_IMAGES="${AMD_IMAGE} ${ARM_IMAGE}"
          docker pull ${IMAGE} || docker buildx imagetools create -t ${IMAGE} ${PLATFORM_IMAGES}

      - name: Logout of DockerHub registry
        run: docker logout

      - name: Annotate image name
        run: echo "::notice::Built and pushed multiplatform image [${IMAGE}]"

      - name: Summary report
        if: ${{ inputs.summary }}
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ### Multiplatform Image Built and Pushed
          \`${IMAGE}\`
          EOF
