name: Idempotent Buildx and Push Multiplatform Image

on:
  workflow_call:

    secrets:
      registry_u:
        description: The username for the docker login
        required: true
      registry_p:
        description: The password (PAT) for the docker login
        required: true

    inputs:
      image:
        description: The name of the image to build and push
        required: true
        type: string
      platforms:
        description: The image platforms to build
        required: true
        type: string
      buildopts:
        description: Optional docker buildx options
        type: string
      runner:
        description: "The type of runner for this workflow (Default: ubuntu-latest)"
        required: false
        type: string
        default: ubuntu-latest

jobs:

  pull-or-buildx-and-push-image:
    name: Build and Push (Once) Multiplatform Image
    runs-on: ${{ inputs.runner }}
    env:
      IMAGE: ${{ inputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Image name
        run: echo "Image name [${IMAGE}]"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: If not pull image, buildx and push image
        env:
          DOCKER_BUILDKIT: 1
          BUILDOPTS: ${{ inputs.buildopts }}
          PLATFORMS: ${{ inputs.platforms }}
        run: docker pull ${IMAGE} || (docker buildx build --no-cache ${BUILDOPTS} --push --platform ${PLATFORMS} --tag ${IMAGE} .)

      - name: Logout of DockerHub registry
        run: docker logout

      - name: Annotate image name
        run: echo "::notice::Built and pushed image [${IMAGE}] for platforms [${{ inputs.platforms }}]"
