name: Idempotent Copy (Promote) Image

on:
  workflow_call:
    inputs:
      source_image:
        required: true
        type: string
      target_image:
        required: true
        type: string
    secrets:
      registry_u:
        required: true
      registry_p:
        required: true

jobs:

  pull-or-pull-and-push-images:
    name: Pull or Pull and Push Images
    runs-on: ubuntu-latest
    env:
      SOURCE_IMAGE: ${{ inputs.source_image }}
      TARGET_IMAGE: ${{ inputs.target_image }}

    steps:
      - name: Install regctl registry tool
        run: |
          curl -fsSL "https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64" >regctl

      - name: Make regctl executable
        run: chmod 755 regctl

      - name: Testing ls directory
        run: ls -al

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.registry_p }} | docker login -u ${{ secrets.registry_u }} --password-stdin

      - name: If the target image does not exist, copy source image to target image
        run: docker pull ${TARGET_IMAGE} || ./regctl image copy ${SOURCE_IMAGE} ${TARGET_IMAGE}

      - name: Logout of DockerHub Registry
        run: docker logout
