name: Copy Image To Latest

on:
  workflow_call:
    inputs:
      runner:
        description: "The type of runner for this workflow (Default: ubuntu-latest)"
        required: false
        type: string
        default: ubuntu-latest
      image:
        description: The image to copy to latest
        required: true
        type: string
    secrets:
      registry_u:
        description: The username for the docker login
        required: true
      registry_p:
        description: The password (PAT) for the docker login
        required: true

jobs:

  strip-tag-from-image:
    name: Strip Tag
    runs-on: ${{ inputs.runner }}
    env:
      IMAGE: ${{ inputs.image }}
    outputs:
      image_name_only: ${{ steps.strip-tag.outputs.image_no_tag }}
    steps:
      - id: strip-tag
        run: echo "image_no_tag=$(echo ${IMAGE%%:*})" >> $GITHUB_OUTPUT

  output-stripped-image:
    name: Stripped Image Name
    runs-on: ${{ inputs.runner }}
    needs: strip-tag-from-image
    steps:
      - name: Image name and stripped
        run: |
          echo "image_name      : ${{ inputs.image }}"
          echo "image_name_only : ${{ needs.strip-tag-from-image.outputs.image_name_only }}"

  copy-image-to-latest:
    name: Copy Image:Tag to Image:latest
    needs: strip-tag-from-image
    uses: ./.github/workflows/copy_image.yml
    with:
      runner: ${{ inputs.runner }}
      source_image: ${{ inputs.image }}
      target_image: "${{ needs.strip-tag-from-image.outputs.image_name_only }}:latest"
    secrets:
      registry_u: ${{ secrets.registry_u }}
      registry_p: ${{ secrets.registry_p }}
