name: Merged Branch and Last Commit SHA of Branch

on:
  workflow_call:

    outputs:
      branch:
        value: ${{ jobs.merged-branch-commit.outputs.branch }}
      commit:
        value: ${{ jobs.merged-branch-commit.outputs.commit }}

jobs:
  merged-branch-commit:
    name: Generate merged branch and branch last commit
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.getbranch.outputs.branch }}
      commit: ${{ steps.getcommit.outputs.commit }}

    steps:
      - uses: actions/checkout@v1

      - name: Output get branch
        run: echo "$(git log -1 --pretty=%B | grep 'Merge pull request' | sed 's/^[^/]*\///')"
      - name: Output get last commit
        run: echo "$(git log -n 1 --skip 1 --pretty=format:"%H")"

      - id: getbranch
        run: echo "::set-output name=branch::$(git log -1 --pretty=%B | grep 'Merge pull request' | sed 's/^[^/]*\///')"
      - id: getcommit
        run: echo "::set-output name=commit::$(git log -n 1 --skip 1 --pretty=format:"%H")"
