name: Display Basic Git and GitHub (Actions) Info

on:
  workflow_call:
    inputs:
      runner:
        description: "The type of runner for this workflow (Default: ubuntu-latest)"
        required: false
        type: string
        default: ubuntu-latest

jobs:
  git-github-info:
    name: Git and GitHub Information
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git log
        run: git log

      - name: Last git commit (SHA)
        run: echo "$(git log -1 --format="%H" | grep -v -e '^$')"

      - name: Last git commit message
        run: echo "$(git log -1 --format="%B" | grep -v -e '^$')"

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
