name: On Push (Merge) Workflow Checks
on:
  push:
    branches:
      - main

jobs:

# The get_merged_branch_last_commit workflow can really only be tested
# on a merge commit
  branch-and-last-commit:
    uses: brianjbayer/actions-image-cicd/.github/workflows/get_merged_branch_last_commit.yml@main

  push-norm-branch:
    needs: [branch-and-last-commit]
    uses: brianjbayer/actions-image-cicd/.github/workflows/normalize_for_image_name.yml@main
    with:
      raw_name: ${{ needs.branch-and-last-commit.outputs.branch }}

  branch-and-last-commit-merged-info:
    needs: [branch-and-last-commit, push-norm-branch]
    runs-on: ubuntu-latest
    env:
      BRANCH_LAST_COMMIT: ${{ needs.branch-and-last-commit.outputs.commit }}
      BRANCH: ${{ needs.branch-and-last-commit.outputs.branch }}
      NORM_BRANCH: ${{ needs.push-norm-branch.outputs.name }}

    steps:
      - name: Output last commit of merged branch env var
        run: echo "BRANCH_LAST_COMMIT=[${BRANCH_LAST_COMMIT}]"
      - name: Output merged branch env var
        run: echo "BRANCH=[${BRANCH}]"
      - name: Output normalized merged branch env var
        run: echo "NORM_BRANCH=[${NORM_BRANCH}]"

# Ensure last branch commit-tagged image exists
# This should demonstrate impotence in the output
# if the commit was created as part of PR job
  ensure-last-branch-build-push-commit-image:
    needs: [branch-and-last-commit, push-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/build_push_image.yml@main
    with:
      image: ${{ github.repository }}_${{ needs.push-norm-branch.outputs.name }}_push:${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  ensure-last-branch-buildx-push-commit-image:
    needs: [branch-and-last-commit, push-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/buildx_push_image.yml@add-multi-arch-buildx
    with:
      image: ${{ github.repository }}_${{ needs.push-norm-branch.outputs.name }}:${{ needs.branch-and-last-commit.outputs.commit }}
      platforms: "linux/amd64,linux/arm64"
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  pull-push-image-branch-last-commit-to-prod:
    needs: [branch-and-last-commit, ensure-last-branch-build-push-commit-image, push-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/pull_push_image.yml@main
    with:
      pull_as: ${{ github.repository }}_${{ needs.push-norm-branch.outputs.name }}_push:${{ needs.branch-and-last-commit.outputs.commit }}
      push_as: ${{ github.repository }}_push:${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  copy-image-branch-last-commit-to-prod:
    needs: [branch-and-last-commit, ensure-last-branch-buildx-push-commit-image, push-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/copy_image.yml@add-multi-arch-buildx
    with:
      source_image: ${{ github.repository }}_${{ needs.push-norm-branch.outputs.name }}:${{ needs.branch-and-last-commit.outputs.commit }}
      target_image: ${{ github.repository }}:${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  pull-push-image-branch-last-commit-to-prod-latest:
    needs: [branch-and-last-commit, pull-push-image-branch-last-commit-to-prod]
    uses: brianjbayer/actions-image-cicd/.github/workflows/pull_push_latest_image.yml@main
    with:
      image_name: ${{ github.repository }}_push
      image_tag: ${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  copy-image-branch-last-commit-to-prod-latest:
    needs: [branch-and-last-commit, copy-image-branch-last-commit-to-prod]
    uses: uses: brianjbayer/actions-image-cicd/.github/workflows/copy_image_to_latest.yml@add-multi-arch-buildx
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ needs.branch-and-last-commit.outputs.commit }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
