name: Merge
on:
  push:
    branches:
      - main

jobs:

  detect-changed-files:
    name: Detect Changed Files Using Git
    uses: ./.github/workflows/git_detect_changed_files.yml
    with:
      file_pattern: git_detect_changed_files.yml

  check-detect-changed-files:
    name: Check Detect Changed Files
    runs-on: ubuntu-latest
    needs: detect-changed-files
    steps:
      - name: Check any changed
        run: |
          if [ "${{ needs.detect-changed-files.outputs.any_changed }}" = "true" ]; then
            echo "Changed files detected "
          else
            echo "No Changed files detected"
          fi

  # --- Image Names ---

  branch-and-last-commit:
    name: Merged Branch and Last Commit
    uses: ./.github/workflows/get_merged_branch_last_commit.yml

  merged-image-names:
    name: Merged (Branch) Image Names
    needs:
      - branch-and-last-commit
    uses: ./.github/workflows/image_names.yml
    with:
      add_branch_name: true
      branch_name: ${{ needs.branch-and-last-commit.outputs.branch }}
      tag: ${{ needs.branch-and-last-commit.outputs.commit }}

  production-image-names:
    name: Production Image Names
    needs:
      - branch-and-last-commit
    uses: ./.github/workflows/image_names.yml
    with:
      tag: ${{ needs.branch-and-last-commit.outputs.commit }}

  latest-tag:
    name: Latest Tag
    uses: ./.github/workflows/latest_tag.yml

  # --- Promote Production Images ---

  # Promote Deployment Image
  promote-merged-deploy-image:
    name: Promote Merged Deployment Image to Production
    needs:
      - merged-image-names
      - production-image-names
    uses: ./.github/workflows/copy_image.yml
    with:
      source_image: ${{ needs.merged-image-names.outputs.vetted_image }}
      target_image: ${{ needs.production-image-names.outputs.vetted_image }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  promote-merged-deploy-image-to-latest:
    name: Promote Latest Deployment Image
    needs:
      - promote-merged-deploy-image
      - production-image-names
      - latest-tag
    uses: ./.github/workflows/copy_image.yml
    with:
      source_image: ${{ needs.production-image-names.outputs.vetted_image }}
      target_image: "${{ needs.production-image-names.outputs.vetted_repository }}:${{ needs.latest-tag.outputs.tag }}"
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # --- Delete PR Branch Image Repositories ---

  delete-pr-branch-image-repositories:
    name: Delete PR Branch Image Repositories
    needs:
    - merged-image-names
    - promote-merged-deploy-image-to-latest
    uses: ./.github/workflows/delete_docker_hub_repositories.yml
    with:
      repositories: '[ "${{ needs.merged-image-names.outputs.vetted_repository }}" ]'
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
