name: PR

on:
  pull_request:
    branches:
      - main

jobs:

  check-git_github_info:
    uses: ./.github/workflows/git_github_info.yml

  detect-changed-files:
    name: Detect Changed Files Using Git
    uses: ./.github/workflows/git_detect_changed_files.yml
    with:
      file_pattern: git_detect_changed_files.yml

  check-detect-changed-files:
    name: Check Detect Changed Files
    runs-on: ubuntu-latest
    needs: detect-changed-files
    steps:
      - name: Check any changed
        run: |
          if [ "${{ needs.detect-changed-files.outputs.any_changed }}" = "true" ]; then
            echo "Changed files detected "
          else
            echo "No Changed files detected"
          fi

  # --- Image Name Normalizer ---

  normalize-valid-image-name:
    uses: ./.github/workflows/normalize_for_image_name.yml
    with:
      raw_name: valid-lowercase-dashes-numbers-22

  check-valid-normalize_for_image_name:
    needs: [normalize-valid-image-name]
    runs-on: ubuntu-latest
    env:
      NORM_NAME: ${{ needs.normalize-valid-image-name.outputs.name }}
    steps:
      - name: Output normalized name
        run: echo "NORM_NAME=[${NORM_NAME}]"
      - name: Verify normalized name
        run: test "$NORM_NAME" = 'valid-lowercase-dashes-numbers-22'

  normalize-invalid-image-name:
    uses: ./.github/workflows/normalize_for_image_name.yml
    with:
      raw_name: "  Dependabot/bundler//nokogiri-1.13.4  "

  check-invalid-normalize_for_image_name:
    needs: [normalize-invalid-image-name]
    runs-on: ubuntu-latest
    env:
      NORM_NAME: ${{ needs.normalize-invalid-image-name.outputs.name }}
    steps:
      - name: Output normalized name
        run: echo "NORM_NAME=[${NORM_NAME}]"
      - name: Verify normalized name
        run: test "$NORM_NAME" = 'dependabot-bundler-nokogiri-1-13-4'

  # -- PR Names ---

  pr-image-names-no-branch:
    name: Generate PR Image Names
    uses: ./.github/workflows/image_names.yml

  check-pr-image-names-no-branch:
    name: Verify PR Image Names
    runs-on: ubuntu-latest
    needs: pr-image-names-no-branch
    env:
      DEV_IMAGE: ${{ needs.pr-image-names-no-branch.outputs.dev_image }}
      UNVETTED_IMAGE: ${{ needs.pr-image-names-no-branch.outputs.unvetted_image }}
      VETTED_IMAGE: ${{ needs.pr-image-names-no-branch.outputs.vetted_image }}
    steps:
      - name: Image Names
        run: |
          echo "Dev Image Name      : ${DEV_IMAGE}"
          echo "Unvetted Image Name : ${UNVETTED_IMAGE}"
          echo "Vetted Image Name   : ${VETTED_IMAGE}"
      - name: Verify Dev Image Name
        run: test "$DEV_IMAGE" = "${{ github.repository }}-dev:${{ github.event.pull_request.head.sha }}"
      - name: Verify Unvetted Image Name
        if: ${{ success() || failure() }}
        run: test "$UNVETTED_IMAGE" = "${{ github.repository }}-unvetted:${{ github.event.pull_request.head.sha }}"
      - name: Verify Vetted Image Name
        if: ${{ success() || failure() }}
        run: test "$VETTED_IMAGE" = "${{ github.repository }}:${{ github.event.pull_request.head.sha }}"

  pr-image-names-with-branch:
    name: Generate PR (Branch) Image Names
    uses: ./.github/workflows/image_names.yml
    with:
      add_branch_name: true

  check-pr-image-names-with-branch:
    name: Verify PR (Branch) Image Names
    runs-on: ubuntu-latest
    needs: pr-image-names-with-branch
    env:
      DEV_IMAGE: ${{ needs.pr-image-names-with-branch.outputs.dev_image }}
      UNVETTED_IMAGE: ${{ needs.pr-image-names-with-branch.outputs.unvetted_image }}
      VETTED_IMAGE: ${{ needs.pr-image-names-with-branch.outputs.vetted_image }}
    steps:
      - name: Image Names
        run: |
          echo "Dev Image Name      : ${DEV_IMAGE}"
          echo "Unvetted Image Name : ${UNVETTED_IMAGE}"
          echo "Vetted Image Name   : ${VETTED_IMAGE}"
      - name: Verify Dev Image Name
        run: test "$DEV_IMAGE" = "${{ github.repository }}_${{ github.head_ref }}-dev:${{ github.event.pull_request.head.sha }}"
      - name: Verify Unvetted Image Name
        if: ${{ success() || failure() }}
        run: test "$UNVETTED_IMAGE" = "${{ github.repository }}_${{ github.head_ref }}-unvetted:${{ github.event.pull_request.head.sha }}"
      - name: Verify Vetted Image Name
        if: ${{ success() || failure() }}
        run: test "$VETTED_IMAGE" = "${{ github.repository }}_${{ github.head_ref }}:${{ github.event.pull_request.head.sha }}"

  pr-image-names-override-branch:
    name: Override PR Branch Image Names
    uses: ./.github/workflows/image_names.yml
    with:
      add_branch_name: true
      branch_name: MY-BRANCH

  check-pr-image-names-with-override-branch:
    name: Verify Override Branch Image Names
    runs-on: ubuntu-latest
    needs: pr-image-names-override-branch
    env:
      DEV_IMAGE: ${{ needs.pr-image-names-override-branch.outputs.dev_image }}
      UNVETTED_IMAGE: ${{ needs.pr-image-names-override-branch.outputs.unvetted_image }}
      VETTED_IMAGE: ${{ needs.pr-image-names-override-branch.outputs.vetted_image }}
      NORM_BRANCH: my-branch
    steps:
      - name: Image Names
        run: |
          echo "Dev Image Name      : ${DEV_IMAGE}"
          echo "Unvetted Image Name : ${UNVETTED_IMAGE}"
          echo "Vetted Image Name   : ${VETTED_IMAGE}"
      - name: Verify Dev Image Name
        run: test "$DEV_IMAGE" = "${{ github.repository }}_${NORM_BRANCH}-dev:${{ github.event.pull_request.head.sha }}"
      - name: Verify Unvetted Image Name
        if: ${{ success() || failure() }}
        run: test "$UNVETTED_IMAGE" = "${{ github.repository }}_${NORM_BRANCH}-unvetted:${{ github.event.pull_request.head.sha }}"
      - name: Verify Vetted Image Name
        if: ${{ success() || failure() }}
        run: test "$VETTED_IMAGE" = "${{ github.repository }}_${NORM_BRANCH}:${{ github.event.pull_request.head.sha }}"

  # --- Build/Push Multi-platform Image ---

  buildx_push_amd_arm_image:
    name: Build Multiplatform(amd/arm) Image
    needs: pr-image-names-with-branch
    uses: ./.github/workflows/buildx_amd_arm_image.yml
    with:
      image: ${{ needs.pr-image-names-with-branch.outputs.unvetted_image }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # --- Promote Multi-platform Image ---

  copyx_image:
    name: Promote (Copy) Multi-platform) Image
    needs:
      - pr-image-names-with-branch
      - buildx_push_amd_arm_image
    uses: ./.github/workflows/copy_image.yml
    with:
      source_image: ${{ needs.pr-image-names-with-branch.outputs.unvetted_image }}
      target_image: ${{ needs.pr-image-names-with-branch.outputs.vetted_image }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  copyx_image_to_latest:
    name: Promote (Copy) Latest Multi-platform) Image
    needs:
      - pr-image-names-with-branch
      - copyx_image
    uses: ./.github/workflows/copy_image_to_latest.yml
    with:
      image: ${{ needs.pr-image-names-with-branch.outputs.vetted_image }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
